### ISSUE TITLE
Using bri.beta.resid for SPDE Beta Regression

### ISSUE THREAD

**Issue by skeyser** [julianfaraway/brinla#5]
Hello Julian,

This "issue" is more of a question. Do you have any existing functions or code that can be used to apply the bri.beta.resid to a spatial model fit in INLA using the "beta" family fitted using the popular SPDE spatial models? 

Tinkering with the code it seems like the matrix sizes become much larger than in the non-spatial matrices calculated in the bri.beta.resid function (presumably due to the sparseness of the distance matrix in the spatial flavor) and this creates a mismatch (and a subsequent error) for the calculation of the residuals. My ultimate goal is to look at semi-variograms between a non-spatial and spatial beta regression model to see how the spatial term deals with the residual autocorrelation.

**Comment by julianfaraway** [comment]
We intentionally excluded spatial models from our book (which this R package supports) so we have not tried that. You might have a look at inlabru or ask the researchers behind it.

**Comment by skeyser** [comment]
Hi Julian,

Okay, that was what I figured. I can look into inquiring from the inlabru/inla spatial folks regarding this issue. I'll go ahead and close this and thanks for the response.
